#!/usr/bin/osascript

## script source : https://github.com/beardedspice/beardedspice/issues/516

if application "Spotify" is running then
  tell application "Spotify"
    set theName to name of the current track
    set theArtist to artist of the current track
    set theAlbum to album of the current track
    set theLength to duration of the current track
    set currPos to player position
    try
      return "♫  " & theName & " - " & theArtist & " - " & currPos & " / " & theLength
    on error err
    end try
  end tell
end if
