#!/bin/bash
result=$(ps -ef | grep quickplay.py | grep python)
if [ -z "$result" -o -f /tmp/goToPandora ] ; then
    /Users/lakshman.narayanan/github/mac_scripts/play_pause_pandora.sh
else
    echo pause | nc -u -w1 127.0.0.1 19999
fi
